-- TẠO CƠ SỞ DỮ LIỆU VÀ SỬ DỤNG
USE MASTER
GO
IF DB_ID('QLSIEUTHI') IS NOT NULL
	DROP DATABASE QLSIEUTHI
GO
CREATE DATABASE QLSIEUTHI
GO
USE QLSIEUTHI
GO

-- BẢNG KHACHHANG
CREATE TABLE KHACHHANG (
    SODIENTHOAI CHAR(10),
    TENKH NVARCHAR(50),
    NGAYSINH DATE,
    NGAYDANGKI DATETIME,
    MUCKHTT NVARCHAR(10),
    CONSTRAINT PKKH PRIMARY KEY (SODIENTHOAI)
);

-- BẢNG LSMUAHANG
CREATE TABLE LSMUAHANG (
    SODIENTHOAI CHAR(10),
    NGAYTHANHTOAN DATETIME,
    THANHTIEN INT,
    CONSTRAINT PKLSMUAHANG PRIMARY KEY (SODIENTHOAI, NGAYTHANHTOAN),
    CONSTRAINT FKLSMUAHANGKH FOREIGN KEY (SODIENTHOAI) REFERENCES KHACHHANG(SODIENTHOAI)
);

-- BẢNG PHIEUMUAHANG
CREATE TABLE PHIEUMUAHANG (
    MAPHIEUMUAHANG VARCHAR(10),
    SODIENTHOAI CHAR(10),
    NGAYHIEULUC DATETIME,
    NGAYHETHAN DATETIME,
    GIATRI INT,
    TRANGTHAI BIT,
    CONSTRAINT PKPMH PRIMARY KEY (MAPHIEUMUAHANG),
    CONSTRAINT FKPMHKH FOREIGN KEY (SODIENTHOAI) REFERENCES KHACHHANG(SODIENTHOAI)
);
CREATE TABLE DANHMUC (
    MADANHMUC INT PRIMARY KEY,
    TENDANHMUC NVARCHAR(50) NOT NULL
);

-- Bảng NhaCungCap: Lưu thông tin nhà cung cấp
CREATE TABLE NHASX (
    MANSX INT PRIMARY KEY, -- Mã của nhà cung cấp
    TENNSX VARCHAR(100) NOT NULL, -- Tên nhà cung cấp
    SDT VARCHAR(20) -- Số điện thoại liên hệ
);

-- Tạo bảng SanPham để lưu thông tin sản phẩm
CREATE TABLE SANPHAM (
    MASP INT PRIMARY KEY,
    TENSP NVARCHAR(255) NOT NULL,
    MOTA NVARCHAR(200),
    MANSX INT,
    GIA DECIMAL(15, 2) NOT NULL,
	TYLEGIAM DECIMAL(5, 2) CHECK (TYLEGIAM >= 0 AND TYLEGIAM <= 100),
    MADANHMUC INT,
	SOLUONGTON INT CHECK (SOLUONGTON >= 0), -- Số lượng hiện có trong kho, không âm
	SLSPTD INT,
    FOREIGN KEY (MADANHMUC) REFERENCES DANHMUC(MADANHMUC),
	FOREIGN KEY (MANSX) REFERENCES NHASX(MANSX)
);

-- Tạo bảng KhuyenMai để lưu thông tin khuyến mãi
-- 1,2,3 flash-sale, combo-sale, member-sale

CREATE TABLE KHUYENMAI (
    MAKHUYENMAI INT PRIMARY KEY,
    TENLOAIKHUYENMAI NVARCHAR(50) NOT NULL,
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,
    SOLUONGTOIDA INT
);

-- đối với member sale 
CREATE TABLE KHUYENMAI_KHACHHANG (
    MAKHUYENMAI INT NOT NULL,
    MUCKHTT NVARCHAR(10) CHECK (MUCKHTT IN (N'THÂN THIẾT', N'ĐỒNG', N'BẠC', N'VÀNG', N'KIM CƯƠNG')),
    TYLEGIAM DECIMAL(5, 2) CHECK (TYLEGIAM >= 0 AND TYLEGIAM <= 100),
    PRIMARY KEY (MAKHUYENMAI, MUCKHTT),
    FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI)
);

-- Tạo bảng SanPham_KhuyenMai để quản lý sản phẩm nào có chương trình khuyến mãi nào
CREATE TABLE SANPHAM_KHUYENMAI (
    MASP INT,
    KHUYENMAIID INT,
    PRIMARY KEY (MASP, KHUYENMAIID),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    FOREIGN KEY (KHUYENMAIID) REFERENCES KHUYENMAI(MAKHUYENMAI)
);

-- Tạo bảng DonHang để lưu thông tin đơn hàng
CREATE TABLE DONHANG (
    DONHANGID INT PRIMARY KEY,
    SO_DIEN_THOAI CHAR(10),
    NGAYMUA DATETIME,
    TONGGIATRI DECIMAL(18, 2),
    FOREIGN KEY (SO_DIEN_THOAI) REFERENCES KHACHHANG(SODIENTHOAI)
);

-- Tạo bảng ChiTietDonHang để lưu chi tiết từng sản phẩm trong đơn hàng
CREATE TABLE CHI_TIET_DON_HANG (
	CHITIETID INT PRIMARY KEY,
    DONHANGID INT,
    MASP INT,
    SOLUONG INT CHECK (SoLuong > 0),
    GIASAPDUNG DECIMAL(18, 2),
    KHUYENMAIID INT,
    FOREIGN KEY (DONHANGID) REFERENCES DONHANG(DONHANGID),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    FOREIGN KEY (KHUYENMAIID) REFERENCES KHUYENMAI(MAKHUYENMAI)
);


-- Bảng DonDatHang: Lưu thông tin đơn đặt hàng
CREATE TABLE DONDATHANG (
    MADDH INT PRIMARY KEY, -- Mã của đơn đặt hàng
    MASP INT NOT NULL, -- Mã của sản phẩm cần đặt
    NGAYDATHANG DATE NOT NULL, -- Ngày đặt hàng
    TRANGTHAI VARCHAR(50), -- Trạng thái của đơn hàng
    SL_DAT INT NOT NULL, -- Số lượng đặt hàng phải lớn hơn 0
	MANSX INT
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP), -- Liên kết đến bảng SanPham
	FOREIGN KEY (MANSX) REFERENCES NHASX(MANSX)
);

-- Bảng NhanHang: Lưu thông tin các lần nhận hàng
CREATE TABLE NHANHANG (
    MANH INT PRIMARY KEY, -- Mã của bản ghi nhận hàng
    MADDH INT NOT NULL, -- Mã của đơn đặt hàng
    NGAYNHAN DATE NOT NULL, -- Ngày nhận hàng
    SL_NHAN INT NOT NULL, -- Số lượng đã nhận, không âm
    FOREIGN KEY (MADDH) REFERENCES DONDATHANG(MADDH) -- Liên kết đến bảng DonDatHang
);
-- Bảng BaoCaoHangNgay: Lưu trữ báo cáo tổng quan hàng ngày
CREATE TABLE BAOCAONGAY (
    NGAYBAOCAO DATE,                    
    TONGKHACHHANG INT DEFAULT 0 CHECK (TongKhachHang >= 0),                    
    TONGDOANHTHU INT DEFAULT 0.00 CHECK (TongDoanhThu >= 0),
	constraint PK_BCHN primary key(NGAYBAOCAO)
);

-- Bảng BaoCaoSanPham: Lưu trữ báo cáo chi tiết cho từng sản phẩm
CREATE TABLE BAOCAOSP (
    NGAYBAOCAO DATE,                               
    MASP INT,                                  
    SLBAN INT DEFAULT 0 CHECK (SLBAN >= 0),                       
    SLKHACHHANGMUA INT DEFAULT 0 CHECK (SLKHACHHANGMUA >= 0),                  
    PRIMARY KEY (NGAYBAOCAO, MASP),          
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) 
);
