USE QLSIEUTHI

-- STORED PROCEDURE THÊM MÃ GIẢM GIÁ
CREATE PROCEDURE SPTHEMPMH
    @SODIENTHOAIKH CHAR(10),
    @NGAYHIEULUC DATETIME,
    @NGAYHETHAN DATETIME
AS
BEGIN
    DECLARE @IDPHIEUMUAHANG VARCHAR(10);
    DECLARE @GIATRI INT;
    DECLARE @ISPHIEUMUAHANGEXIST BIT = 1;
    DECLARE @MUCKHTT NVARCHAR(10);

    -- KIỂM TRA NGÀY HIỆU LỰC VÀ NGÀY HẾT HẠN
    IF @NGAYHIEULUC >= @NGAYHETHAN
    BEGIN
        RAISERROR('NGÀY HIỆU LỰC KHÔNG ĐƯỢC LỚN HƠN HOẶC BẰNG NGÀY HẾT HẠN', 16, 1);
        RETURN;
    END

    -- TẠO MÃ PHIEUMUAHANG NGẪU NHIÊN
    WHILE @ISPHIEUMUAHANGEXIST = 1
    BEGIN
        SET @IDPHIEUMUAHANG = RIGHT(CONCAT('0000000000', CAST(ABS(CHECKSUM(NEWID())) % 10000000000 AS VARCHAR(10))), 10);

        -- KIỂM TRA MÃ PHIEUMUAHANG ĐÃ TỒN TẠI CHƯA
        IF NOT EXISTS (SELECT 1 FROM PHIEUMUAHANG WHERE MAPHIEUMUAHANG = @IDPHIEUMUAHANG)
        BEGIN
            SET @ISPHIEUMUAHANGEXIST = 0;
        END
    END

    -- LẤY MỨC KHTT TỪ BẢNG KHACHHANG
    SET @MUCKHTT = (SELECT MUCKHTT FROM KHACHHANG WHERE SODIENTHOAI = @SODIENTHOAIKH);

    -- THIẾT LẬP GIÁ TRỊ DỰA TRÊN MỨC KHTT
    IF @MUCKHTT = N'KIM CƯƠNG'
        SET @GIATRI = 1200000;
    ELSE IF @MUCKHTT = N'BẠCH KIM'
        SET @GIATRI = 700000;
    ELSE IF @MUCKHTT = N'VÀNG'
        SET @GIATRI = 500000;
    ELSE IF @MUCKHTT = N'BẠC'
        SET @GIATRI = 200000;
    ELSE IF @MUCKHTT = N'ĐỒNG'
        SET @GIATRI = 100000;
    ELSE
    BEGIN
        RETURN;
    END

    -- THÊM PHIEUMUAHANG VÀO BẢNG PHIEUMUAHANG
    INSERT INTO PHIEUMUAHANG (MAPHIEUMUAHANG, SODIENTHOAIKH, NGAYHIEULUC, NGAYHETHAN, GIATRI, KHADUNG)
    VALUES (@IDPHIEUMUAHANG, @SODIENTHOAIKH, @NGAYHIEULUC, @NGAYHETHAN, @GIATRI, 1);
END;
