﻿﻿

USE SupermarketDB;
GO


GO
CREATE PROCEDURE SP_XU_LI_DON @MADONHANG NVARCHAR(50)
AS
BEGIN 
	DECLARE @SDT CHAR(10)
	IF EXISTS (SELECT 1 FROM DONHANG AS DH WHERE DH.DONHANGID=@MADONHANG)
		BEGIN

			DECLARE @TONG DECIMAL(18,2)
			DECLARE @GIATRI INT
			DECLARE @NGAYHIEULUC DATE
			DECLARE @NGAYHETHAN DATE
			DECLARE @TRANGTHAI BIT

			SELECT @TONG=SUM(CTDH.GIASAPDUNG)
			FROM CHITIETDONHANG AS CTDH

			SELECT @SDT=DH.SO_DIEN_THOAI
			FROM DONHANG AS DH
			WHERE DH.DONHANGID=@MADONHANG

			IF EXISTS(SELECT 1 FROM PHIEUMUAHANG AS PMH WHERE PMH.SODIENTHOAI=@SDT)
				BEGIN
					SELECT @GIATRI=PMH.GIATRI, @NGAYHETHAN=PMH.NGAYHETHAN, @NGAYHIEULUC=PMH.NGAYHIEULUC, @TRANGTHAI=PMH.TRANGTHAI
					FROM PHIEUMUAHANG AS PMH WHERE PMH.SODIENTHOAI=@SDT

					IF(@NGAYHIEULUC<=GETDATE() AND @NGAYHETHAN>=GETDATE() AND @TRANGTHAI=1)
						BEGIN
							SET @TONG=@TONG-@GIATRI
						END
				END

			UPDATE DONHANG SET TONGGIATRI=@TONG WHERE DONHANGID=@MADONHANG
			UPDATE PHIEUMUAHANG SET TRANGTHAI=0 WHERE SODIENTHOAI=@SDT
		END
	ELSE
		BEGIN
			RAISERROR(N'Không tìm thấy mã đơn hàng',16,1)
		END
END
GO


GO
CREATE PROC TAO_CHI_TIET_DON_HANG @DONHANGID NVARCHAR(50), @MASP INT, @SOLUONG INT
AS
BEGIN
	
	IF EXISTS(SELECT 1 FROM SANPHAM AS SP WHERE SP.MASP=@MASP)
		BEGIN
			IF(@SOLUONG>0)
				BEGIN
					INSERT INTO CHITIETDONHANG (DONHANGID, MASP, SOLUONG) VALUES (@DONHANGID, @MASP, @SOLUONG)
				END
			ELSE
				BEGIN
					RAISERROR(N'Số lượng sản phẩm phải lớn hơn 0',16,1)
				END
		END
	ELSE
		BEGIN
			RAISERROR(N'Không tìm thấy mã sản phẩm phù hợp',16,1)
		END

END
GO

GO
CREATE PROC TIM_UU_DAI_TOT_NHAT @DONHANGID NVARCHAR(5)
AS
BEGIN
	DECLARE @SDT CHAR(10)

	SELECT @SDT=DH.SO_DIEN_THOAI
	FROM DONHANG AS DH
	WHERE DH.DONHANGID=@DONHANGID

	CREATE TABLE #TEMPCT
	(
		MASP INT,
		SOLUONG INT,
		GIA DECIMAL(15,2),
		KHUYENMAIID NVARCHAR(50),
		TYLEGIAM FLOAT,
		GIASAPDUNG DECIMAL(15,2)

	)

	INSERT INTO #TEMPCT(MASP, SOLUONG) 
	SELECT CTDH.MASP, CTDH.SOLUONG
	FROM CHITIETDONHANG AS CTDH
	WHERE CTDH.DONHANGID=@DONHANGID

	UPDATE T
	SET T.GIA = SP.GIA
	FROM #TEMPCT AS T
	JOIN SANPHAM AS SP ON SP.MASP = T.MASP;

	--Tìm flash-sale tốt nhất cho các sản phẩm
	SELECT T.MASP, KM.MAKHUYENMAI, MAX(KM.TYLEGIAM) AS TYLEGIAM
	INTO #TEMP2
	FROM #TEMPCT AS T
	JOIN SANPHAM_KHUYENMAI AS SPKM ON SPKM.MASP=T.MASP
	JOIN KHUYENMAI AS KM ON KM.MAKHUYENMAI=SPKM.KHUYENMAIID
	WHERE KM.MALOAIKHUYENMAI=1
	GROUP BY T.MASP, KM.MAKHUYENMAI

	UPDATE T
	SET T.KHUYENMAIID = T2.MAKHUYENMAI, T.TYLEGIAM = T2.TYLEGIAM
	FROM #TEMPCT AS T
	JOIN #TEMP2 AS T2 ON T.MASP = T2.MASP;

	--Nếu toàn bộ sản phẩm đều có flash-sale
	IF NOT EXISTS (SELECT 1 FROM #TEMPCT AS T WHERE T.KHUYENMAIID IS NULL)
		BEGIN
			UPDATE #TEMPCT
			SET GIASAPDUNG = GIA * (1 - (TYLEGIAM / 100)) * 
                 CASE 
                     WHEN SOLUONG > 3 THEN 3
                     ELSE SOLUONG
                 END;
		END
	ELSE
		BEGIN
			--Áp dụng combo-sale cho sản phẩm có số lượng 2 trở lên
			SELECT T.MASP, KM.MAKHUYENMAI, MAX(KM.TYLEGIAM) AS TYLEGIAM
			INTO #TEMP3
			FROM #TEMPCT AS T
			JOIN SANPHAM_KHUYENMAI AS SPKM ON SPKM.MASP=T.MASP
			JOIN KHUYENMAI AS KM ON KM.MAKHUYENMAI=SPKM.KHUYENMAIID
			WHERE KM.MALOAIKHUYENMAI=2 AND T.KHUYENMAIID IS NULL AND T.SOLUONG>=2
			GROUP BY T.MASP, KM.MAKHUYENMAI

			UPDATE T
			SET T.KHUYENMAIID = T3.MAKHUYENMAI, T.TYLEGIAM = T3.TYLEGIAM
			FROM #TEMPCT AS T
			JOIN #TEMP3 AS T3 ON T.MASP = T3.MASP


			UPDATE #TEMPCT
			SET GIASAPDUNG = T.GIA * (1 - (T.TYLEGIAM / 100)) * 2
			FROM #TEMPCT AS T
			JOIN #TEMP3 AS T3 ON T.MASP=T3.MASP


			IF EXISTS (SELECT 1 FROM #TEMPCT AS T WHERE T.KHUYENMAIID IS NULL)
				BEGIN
					CREATE TABLE #TEMP4 (
					MASP1 INT,
					MASP2 INT,
					MAKHUYENMAI NVARCHAR(50),
					TYLEGIAM FLOAT
					)

					IF EXISTS (
					SELECT 1
					FROM SANPHAM_KHUYENMAI AS SP1
					JOIN SANPHAM_KHUYENMAI AS SP2 
						ON SP1.KHUYENMAIID = SP2.KHUYENMAIID -- Cùng mã khuyến mãi
						AND SP1.MASP != SP2.MASP             -- Đảm bảo không trùng lặp cặp sản phẩm
					JOIN KHUYENMAI AS KM 
						ON SP1.KHUYENMAIID = KM.MAKHUYENMAI
					WHERE KM.MALOAIKHUYENMAI = 2 -- Combo-sale
						AND KM.NGAYBATDAU <= GETDATE() 
						AND KM.NGAYKETTHUC >= GETDATE()
						AND SP1.SLAPDUNG > 0 AND SP2.SLAPDUNG > 0
				)
					BEGIN
						INSERT INTO #TEMP4 (MASP1, MASP2, MAKHUYENMAI, TYLEGIAM)
						SELECT 
							SP1.MASP AS MASP1,
							SP2.MASP AS MASP2,
							KM.MAKHUYENMAI,
							KM.TYLEGIAM
						FROM SANPHAM_KHUYENMAI AS SP1
						JOIN SANPHAM_KHUYENMAI AS SP2 ON SP1.KHUYENMAIID = SP2.KHUYENMAIID
							AND SP1.MASP != SP2.MASP
						JOIN KHUYENMAI AS KM ON SP1.KHUYENMAIID = KM.MAKHUYENMAI
						WHERE KM.MALOAIKHUYENMAI = 3
							AND KM.NGAYBATDAU <= GETDATE()
							AND KM.NGAYKETTHUC >= GETDATE()
							AND SP1.SLAPDUNG > 0 AND SP2.SLAPDUNG > 0
							AND KM.TYLEGIAM = ( -- Chọn mức giảm giá cao nhất
								SELECT MAX(KM2.TYLEGIAM)
								FROM KHUYENMAI AS KM2
								JOIN SANPHAM_KHUYENMAI AS SPKM 
									ON KM2.MAKHUYENMAI = SPKM.KHUYENMAIID
								WHERE SPKM.MASP IN (SP1.MASP, SP2.MASP)
								  AND KM2.MALOAIKHUYENMAI = 3
								  AND KM2.NGAYBATDAU <= GETDATE()
								  AND KM2.NGAYKETTHUC >= GETDATE()
							);
					END;

					UPDATE T
					SET T.KHUYENMAIID = T4.MAKHUYENMAI, T.TYLEGIAM = T4.TYLEGIAM
					FROM #TEMPCT AS T
					JOIN #TEMP4 AS T4 ON T.MASP = T4.MASP1 OR T.MASP=T4.MASP2
				

					UPDATE #TEMPCT
					SET GIASAPDUNG = T.GIA * (1 - (T.TYLEGIAM / 100)) * 
						CASE
							WHEN T.SOLUONG > 3 THEN 3
							ELSE T.SOLUONG
						END
					FROM #TEMPCT AS T
					JOIN #TEMP4 AS T4 ON T.MASP=T4.MASP1 OR T.MASP=T4.MASP2

					IF EXISTS (SELECT 1 FROM #TEMPCT AS T WHERE T.KHUYENMAIID IS NULL)
						BEGIN
							DECLARE @MUCKH NVARCHAR(50)
							IF EXISTS (SELECT 1 FROM KHACHHANG AS KH WHERE KH.SODIENTHOAI=@SDT)
								BEGIN
									CREATE TABLE #TEMP5 (
									MASP INT,
									MAKHUYENMAI NVARCHAR(50),
									TYLEGIAM FLOAT
									)

									INSERT INTO #TEMP5(MASP, MAKHUYENMAI)
									SELECT T.MASP, SPKM.KHUYENMAIID
									FROM #TEMPCT AS T
									JOIN SANPHAM_KHUYENMAI AS SPKM ON SPKM.MASP=T.MASP
									JOIN KHUYENMAI AS KM ON SPKM.KHUYENMAIID=KM.MAKHUYENMAI
									WHERE T.KHUYENMAIID IS NULL AND KM.MALOAIKHUYENMAI=3

									SELECT @MUCKH=KH.MUCKHTT
									FROM KHACHHANG AS KH
									WHERE KH.SODIENTHOAI=@SDT

									DECLARE @TYLEGIAM FLOAT
									SELECT @TYLEGIAM=KMKH.TYLEGIAM
									FROM KHUYENMAI_KHACHHANG AS KMKH
									WHERE KMKH.MUCKHTT=@MUCKH

									UPDATE #TEMP5 SET TYLEGIAM=@TYLEGIAM

									UPDATE T
									SET T.KHUYENMAIID = T5.MAKHUYENMAI, T.TYLEGIAM = T5.TYLEGIAM
									FROM #TEMPCT AS T
									JOIN #TEMP5 AS T5 ON T.MASP = T5.MASP

									UPDATE #TEMPCT
									SET GIASAPDUNG = T.GIA * (1 - (T.TYLEGIAM / 100)) *
										CASE
											WHEN T.SOLUONG>3 THEN 3
											ELSE T.SOLUONG
										END
									FROM #TEMPCT AS T
									JOIN #TEMP5 AS T5 ON T.MASP=T5.MASP
								
								END
						END
					ELSE
						BEGIN
							UPDATE #TEMPCT
							SET GIASAPDUNG=GIA
							FROM #TEMPCT AS T
							JOIN #TEMP5 AS T5 ON T.MASP=T5.MASP
							
						END
				END
				END	
	UPDATE CHITIETDONHANG
	SET KHUYENMAIID=T.KHUYENMAIID, GIASAPDUNG=T.GIASAPDUNG
	FROM CHITIETDONHANG AS CTDH
	JOIN #TEMPCT AS T ON T.MASP=CTDH.MASP
END
GO


















































